export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT='SET_INGREDIENT';
export const FETCH_ING_FAILED='FETCH_ING_FAILED';

export const PURCHASE_SUCCESS='PURCHASE_SUCCESS';
export const PURCHASE_FAILURE='PURCHASE FAILURE';
export const PURCHASE_START='PURCHASE START';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE='FETCH_ORDERS_FAILURE';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAILURE='AUTH_FAILURE';

export const LOG_OUT='LOG_OUT';
export const SET_AUTH_REDIRECT='SET_AUTH_REDIRECT';